### ISSUE TITLE
Missing steps for installation

### ISSUE THREAD

**Issue by maaaaz** [CERT-Solucom/certitude#15]
Hello,
I tried to install Certitude from scratch in a virtualenv named `venvcertitude` on an Ubuntu 16.10 virtual machine from osboxes.org. 
Here are my feedbacks:
* `requirements.txt` needs `pyopenssl` module which needs `cryptography` module, which needs OpenSSL headers. Without them you have that error:
```
Building wheels for collected packages: cryptography
[...]
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-lMBuS3/python2.7-2.7.12=. -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c build/temp.linux-x86_64-2.7/_openssl.c -o build/temp.linux-x86_64-2.7/build/temp.linux-x86_64-2.7/_openssl.o
  build/temp.linux-x86_64-2.7/_openssl.c:434:30: fatal error: openssl/opensslv.h: No such file or directory
   #include <openssl/opensslv.h>
                                ^
  compilation terminated.
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
 ----------------------------------------
  Running setup.py clean for cryptography
Failed to build cryptography
```
=> so `apt-get install libssl-dev` on debian or `yum install openssl-devel` is a prerequisite

* `gen-cert-for-me.bat`: why there is not a Linux shell version of that script ?
* `python main.py init` leads to that error:
```
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    main()
  File "main.py", line 62, in main
    from helpers import init
  File "/opt/certitude/helpers/init.py", line 36, in <module>
    import crypto
  File "/opt/certitude/helpers/crypto.py", line 26, in <module>
    from Crypto.Cipher import AES
ImportError: No module named Crypto.Cipher
```
=> so `pip install pycrypto` is needed. Add `pycrypto` in your `requirements.txt`

Cheers.

**Comment by Iansus** [comment]
See https://github.com/CERT-W/certitude/wiki/01.--Install-guide
