### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by firebitsbr** [CERT-Solucom/certitude#25]
sh interface.sh 
api                  : INFO     Web interface starting
werkzeug             : INFO      * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
werkzeug             : INFO      * Restarting with stat
Traceback (most recent call last):
  File "main.py", line 81, in <module>
    main()
  File "main.py", line 65, in main
    from components.interface import web
  File "/root/certitude/components/interface/web.py", line 137, in <module>
    bokeh_process = subprocess.Popen(['bokeh', 'serve', 'crossbokeh.py'], stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by Iansus** [comment]
Hi,
Can you run the following commands on your test environment?
```
which bokeh
pip show bokeh
```
